{
	"name": "CVE-2024-53432",
	"description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
	"type": "none",
	"severity": "none",
	"state": "published",
	"references": [
		"https://github.com/PointCloudLibrary/pcl/issues/6162"
	],
	"datetime": "2025-02-06 12:35:24",
	"connections": [],
	"devices": [],
	"distributions": [
		{
			"name": "debian",
			"version": "bookworm",
			"vendor": "debian-bookworm"
		},
		{
			"name": "debian",
			"version": "bullseye",
			"vendor": "debian-bullseye"
		},
		{
			"name": "debian",
			"version": "sid",
			"vendor": "debian-sid"
		},
		{
			"name": "debian",
			"version": "trixie",
			"vendor": "debian-trixie"
		}
	],
	"packages": [
		{
			"name": "pcl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		}
	],
	"products": [],
	"programs": [],
	"weaknesses": [
		{
			"name": "CWE-754",
			"impact": "any",
			"scope": "any"
		}
	]
}