{
	"name": "CVE-2024-31904",
	"description": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 integration nodes could allow an authenticated user to cause a denial of service due to an uncaught exception.  IBM X-Force ID:  289647.",
	"type": "none",
	"severity": "none",
	"state": "published",
	"references": [
		"https://exchange.xforce.ibmcloud.com/vulnerabilities/289647",
		"https://www.ibm.com/support/pages/node/7154607"
	],
	"datetime": "2025-02-06 12:35:09",
	"connections": [],
	"devices": [],
	"distributions": [],
	"packages": [],
	"products": [],
	"programs": [],
	"weaknesses": [
		{
			"name": "CWE-248",
			"impact": "any",
			"scope": "any"
		}
	]
}